# Generated by Django 4.2.3 on 2023-07-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
                ('fecha_precio', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('vendedor', models.CharField(max_length=40)),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.materiales')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('subcategoria', models.CharField(max_length=150)),
                ('materiales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.materiales')),
            ],
        ),
    ]
