# Generated by Django 4.2.3 on 2023-07-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_grupo_subcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='subcategoria',
        ),
    ]
